
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: "6.17.1",
  engine: "272a37d34178c2894197e17273bf937f25acdeac"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.SecretKeyLicenseScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  key: 'key',
  app_name: 'app_name',
  created_at: 'created_at',
  regenerated_at: 'regenerated_at'
};

exports.Prisma.LicenseKeyScalarFieldEnum = {
  id: 'id',
  secret_key_id: 'secret_key_id',
  customer_id: 'customer_id',
  email: 'email',
  code: 'code',
  can_regenerate: 'can_regenerate',
  is_revoked: 'is_revoked',
  created_at: 'created_at',
  updated_at: 'updated_at',
  regenerated_at: 'regenerated_at',
  device_id: 'device_id',
  last_reset_period: 'last_reset_period',
  reset_count: 'reset_count'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  SecretKeyLicense: 'SecretKeyLicense',
  LicenseKey: 'LicenseKey'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "client",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "/home/rezafikkri/Programming/www/priskojrmod-cms/prisma-pjma-db/pjma-db-client",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "debian-openssl-3.0.x",
        "native": true
      },
      {
        "fromEnvVar": null,
        "value": "rhel-openssl-3.0.x"
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "/home/rezafikkri/Programming/www/priskojrmod-cms/prisma-pjma/schema.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": null,
    "schemaEnvPath": "../../.env"
  },
  "relativePath": "../../prisma-pjma",
  "clientVersion": "6.17.1",
  "engineVersion": "272a37d34178c2894197e17273bf937f25acdeac",
  "datasourceNames": [
    "db"
  ],
  "activeProvider": "postgresql",
  "inlineDatasources": {
    "db": {
      "url": {
        "fromEnvVar": "DATABASE_URL_PJMA",
        "value": null
      }
    }
  },
  "inlineSchema": "// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\n// This schema is for priskojrmod_app database\n\ngenerator client {\n  provider      = \"prisma-client-js\"\n  output        = \"../prisma-pjma-db/pjma-db-client\"\n  binaryTargets = [\"native\", \"rhel-openssl-3.0.x\"]\n}\n\ndatasource db {\n  provider  = \"postgresql\"\n  url       = env(\"DATABASE_URL_PJMA\")\n  directUrl = env(\"DIRECT_URL_PJMA\")\n}\n\nmodel SecretKeyLicense {\n  id             Int    @id @default(autoincrement())\n  product_id     String @unique @db.Uuid\n  key            String @db.VarChar(100)\n  app_name       String @db.VarChar(50)\n  created_at     Int\n  regenerated_at Int?\n\n  license_key LicenseKey[]\n\n  @@map(\"secret_key_licenses\")\n}\n\nmodel LicenseKey {\n  id             String           @id @default(uuid(7)) @db.Uuid\n  secret_key     SecretKeyLicense @relation(fields: [secret_key_id], references: [id])\n  secret_key_id  Int\n  customer_id    String           @db.Uuid\n  email          String           @db.VarChar(254)\n  code           String\n  can_regenerate Boolean          @default(false)\n  is_revoked     Boolean          @default(false)\n  created_at     Int\n  updated_at     Int\n  regenerated_at Int?\n\n  device_id         String? @db.VarChar(100)\n  last_reset_period String? @db.VarChar(10)\n  reset_count       Int     @default(0) @db.SmallInt\n\n  @@unique([customer_id, secret_key_id])\n  @@map(\"license_keys\")\n}\n",
  "inlineSchemaHash": "ec01c8bc26e761fe015ae6cf93b4413943f6b11bf2c5ebf6caca7c4992f30d62",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"SecretKeyLicense\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"product_id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"key\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"app_name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"regenerated_at\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"license_key\",\"kind\":\"object\",\"type\":\"LicenseKey\",\"relationName\":\"LicenseKeyToSecretKeyLicense\"}],\"dbName\":\"secret_key_licenses\"},\"LicenseKey\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"secret_key\",\"kind\":\"object\",\"type\":\"SecretKeyLicense\",\"relationName\":\"LicenseKeyToSecretKeyLicense\"},{\"name\":\"secret_key_id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"customer_id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"email\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"code\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"can_regenerate\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"is_revoked\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"created_at\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"updated_at\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"regenerated_at\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"device_id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"last_reset_period\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"reset_count\",\"kind\":\"scalar\",\"type\":\"Int\"}],\"dbName\":\"license_keys\"}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {
    DATABASE_URL_PJMA: typeof globalThis !== 'undefined' && globalThis['DATABASE_URL_PJMA'] || typeof process !== 'undefined' && process.env && process.env.DATABASE_URL_PJMA || undefined
  }
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

