
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: "6.17.1",
  engine: "272a37d34178c2894197e17273bf937f25acdeac"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  role: 'role',
  auth_id: 'auth_id',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  whatsapp_phone_number: 'whatsapp_phone_number',
  picture: 'picture',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.DonationLinkScalarFieldEnum = {
  id: 'id',
  admin_id: 'admin_id',
  currency_code: 'currency_code',
  link: 'link'
};

exports.Prisma.OwnerScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  sm_username: 'sm_username',
  picture: 'picture',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  oauth_id: 'oauth_id',
  is_banned: 'is_banned',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  phone_number: 'phone_number',
  picture: 'picture',
  last_active: 'last_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.LicenseScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.LicenseTranslationScalarFieldEnum = {
  id: 'id',
  license_id: 'license_id',
  language: 'language',
  name: 'name',
  content: 'content'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  category_id: 'category_id',
  admin_id: 'admin_id',
  owner_id: 'owner_id',
  license_id: 'license_id',
  drive_file_id: 'drive_file_id',
  download_link: 'download_link',
  is_published: 'is_published',
  is_pinned: 'is_pinned',
  name: 'name',
  slug: 'slug',
  price_type: 'price_type',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ProductTranslationScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  language: 'language',
  description: 'description'
};

exports.Prisma.ProductVersionScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  version: 'version',
  released_at: 'released_at'
};

exports.Prisma.ProductVersionTranslationScalarFieldEnum = {
  id: 'id',
  product_version_id: 'product_version_id',
  language: 'language',
  changelog: 'changelog'
};

exports.Prisma.ProductDiscountScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  discount: 'discount',
  expired_at: 'expired_at'
};

exports.Prisma.ProductCouponScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  code: 'code',
  discount: 'discount',
  expired_at: 'expired_at'
};

exports.Prisma.ProductImageScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  url: 'url',
  is_thumbnail: 'is_thumbnail',
  width: 'width',
  height: 'height'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  name: 'name',
  download_link: 'download_link',
  file_access_password: 'file_access_password'
};

exports.Prisma.ProductPriceScalarFieldEnum = {
  id: 'id',
  variant_id: 'variant_id',
  currency_code: 'currency_code',
  price: 'price'
};

exports.Prisma.TermsOfServiceScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.TermsOfServiceTranslationScalarFieldEnum = {
  id: 'id',
  terms_of_service_id: 'terms_of_service_id',
  language: 'language',
  content: 'content'
};

exports.Prisma.PrivacyPolicyScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PrivacyPolicyTranslationScalarFieldEnum = {
  id: 'id',
  privacy_policy_id: 'privacy_policy_id',
  language: 'language',
  content: 'content'
};

exports.Prisma.AboutUsScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.AboutUsTranslationScalarFieldEnum = {
  id: 'id',
  about_us_id: 'about_us_id',
  language: 'language',
  content: 'content'
};

exports.Prisma.FaqScalarFieldEnum = {
  id: 'id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.FaqTranslationScalarFieldEnum = {
  id: 'id',
  faq_id: 'faq_id',
  language: 'language',
  title: 'title',
  content: 'content'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  code: 'code',
  customer_id: 'customer_id',
  admin_id: 'admin_id',
  admin_email: 'admin_email',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  currency_code: 'currency_code',
  total_amount: 'total_amount',
  customer_name: 'customer_name',
  customer_email: 'customer_email',
  customer_phone_number: 'customer_phone_number'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  invoice_number: 'invoice_number',
  status: 'status',
  issued_at: 'issued_at',
  voided_at: 'voided_at'
};

exports.Prisma.TransactionDetailScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  product_id: 'product_id',
  product_price_id: 'product_price_id',
  product_coupon_id: 'product_coupon_id',
  quantity: 'quantity',
  product_name: 'product_name',
  product_version: 'product_version',
  product_drive_file_id: 'product_drive_file_id',
  product_download_link: 'product_download_link',
  product_variant: 'product_variant',
  variant_download_link: 'variant_download_link',
  variant_file_access_password: 'variant_file_access_password',
  product_currency_code: 'product_currency_code',
  product_price: 'product_price',
  product_discount: 'product_discount',
  product_coupon_code: 'product_coupon_code',
  product_coupon_discount: 'product_coupon_discount',
  drive_permission_id: 'drive_permission_id',
  share_method: 'share_method',
  shared_at: 'shared_at'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  is_read: 'is_read',
  name: 'name',
  email: 'email',
  message: 'message',
  created_at: 'created_at'
};

exports.Prisma.TestimonialScalarFieldEnum = {
  id: 'id',
  picture: 'picture',
  name: 'name',
  sm_username: 'sm_username',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.TestimonialTranslationScalarFieldEnum = {
  id: 'id',
  testimonial_id: 'testimonial_id',
  language: 'language',
  message: 'message'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.AdminRole = exports.$Enums.AdminRole = {
  owner: 'owner',
  staff: 'staff'
};

exports.CurrencyCode = exports.$Enums.CurrencyCode = {
  IDR: 'IDR',
  USD: 'USD'
};

exports.Language = exports.$Enums.Language = {
  id: 'id',
  en: 'en'
};

exports.PriceType = exports.$Enums.PriceType = {
  paid: 'paid',
  free: 'free'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  pending: 'pending',
  paid: 'paid',
  cancelled: 'cancelled',
  refund: 'refund'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  active: 'active',
  void: 'void'
};

exports.ShareMethod = exports.$Enums.ShareMethod = {
  download_link: 'download_link',
  drive_share: 'drive_share',
  manual_required: 'manual_required'
};

exports.Prisma.ModelName = {
  Admin: 'Admin',
  DonationLink: 'DonationLink',
  Owner: 'Owner',
  Customer: 'Customer',
  License: 'License',
  LicenseTranslation: 'LicenseTranslation',
  Category: 'Category',
  Product: 'Product',
  ProductTranslation: 'ProductTranslation',
  ProductVersion: 'ProductVersion',
  ProductVersionTranslation: 'ProductVersionTranslation',
  ProductDiscount: 'ProductDiscount',
  ProductCoupon: 'ProductCoupon',
  ProductImage: 'ProductImage',
  ProductVariant: 'ProductVariant',
  ProductPrice: 'ProductPrice',
  TermsOfService: 'TermsOfService',
  TermsOfServiceTranslation: 'TermsOfServiceTranslation',
  PrivacyPolicy: 'PrivacyPolicy',
  PrivacyPolicyTranslation: 'PrivacyPolicyTranslation',
  AboutUs: 'AboutUs',
  AboutUsTranslation: 'AboutUsTranslation',
  Faq: 'Faq',
  FaqTranslation: 'FaqTranslation',
  Transaction: 'Transaction',
  Invoice: 'Invoice',
  TransactionDetail: 'TransactionDetail',
  Feedback: 'Feedback',
  Testimonial: 'Testimonial',
  TestimonialTranslation: 'TestimonialTranslation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
